### ISSUE TITLE
404 when UA fails to connect

### ISSUE THREAD

**Issue by shyba** [pixelated-project/pixelated-dispatcher#66]
Steps
--------
* Take a working logged user
* Logout and stop container
* Disconnect from internet (seriously :)
* Login

Expected: Clear error message on login screen

Currently: "Could not connect to instance <username>: HTTP 404: Not Found"

Logs
--------
* On UA container:
```
2015-01-21 20:00:25+0000 [-] ("Can't connect to the requested provider", ConnectionError(ProtocolError('Connection aborted.', gaierror(-2, 'Name or service not known')),))
2015-01-21 20:00:25+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 416, in fireEvent
            DeferredList(beforeResults).addCallback(self._continueFiring)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 306, in addCallback
            callbackKeywords=kw)
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 295, in addCallbacks
            self._runCallbacks()
          File "/usr/lib/python2.7/dist-packages/twisted/internet/defer.py", line 577, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 429, in _continueFiring
            callable(*args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 134, in <lambda>
            reactor.callWhenRunning(lambda: init_app(app, args.home))
          File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 89, in init_app
            leap_session = init_leap_session(app, leap_home)
          File "/usr/lib/python2.7/dist-packages/pixelated/config/app_factory.py", line 73, in init_leap_session
            sys.exit(1)
        exceptions.SystemExit: 1


2015-01-21 20:00:25+0000 [HTTPChannel,0,172.17.42.1] 172.17.42.1 - - [21/Jan/2015:20:00:25 +0000] "GET / HTTP/1.1" 404 233 "-" "Mozilla/5.0 (compatible; pycurl)"
2015-01-21 20:00:26+0000 [HTTPChannel,1,172.17.42.1] 172.17.42.1 - - [21/Jan/2015:20:00:25 +0000] "GET / HTTP/1.1" 404 233 "-" "Mozilla/5.0 (compatible; pycurl)"
2015-01-21 20:00:26+0000 [HTTPChannel,2,172.17.42.1] 172.17.42.1 - - [21/Jan/2015:20:00:26 +0000] "GET / HTTP/1.1" 404 233 "-" "Mozilla/5.0 (compatible; pycurl)"
2015-01-21 20:00:27+0000 [HTTPChannel,3,172.17.42.1] 172.17.42.1 - - [21/Jan/2015:20:00:26 +0000] "GET / HTTP/1.1" 404 233 "-" "Mozilla/5.0 (compatible; pycurl)"
2015-01-21 20:00:27+0000 [HTTPChannel,4,172.17.42.1] 172.17.42.1 - - [21/Jan/2015:20:00:27 +0000] "GET / HTTP/1.1" 404 233 "-" "Mozilla/5.0 (compatible; pycurl)"
2015-01-21 20:00:28+0000 [HTTPChannel,5,172.17.42.1] 172.17.42.1 - - [21/Jan/2015:20:00:27 +0000] "GET / HTTP/1.1" 404 233 "-" "Mozilla/5.0 (compatible; pycurl)"
```

* From syslog:

```
Jan 21 20:39:49 vagrant-debian pixelated.dispatcher: INFO User None logged out
Jan 21 20:39:58 vagrant-debian pixelated.manager: INFO User <username> logged in successfully
Jan 21 20:39:58 vagrant-debian pixelated.dispatcher: INFO Successful login of user <username>
Jan 21 20:39:58 vagrant-debian pixelated.dispatcher: INFO Starting agent for <username>
Jan 21 20:39:58 vagrant-debian pixelated.dispatcher: ERROR Got error from user <username> agent: HTTP 404: Not Found
Jan 21 20:40:03 vagrant-debian pixelated.dispatcher: ERROR Got error from user <username> agent: HTTP 404: Not Found
```

**Comment by re-nobre** [comment]
This is a good idea but it isn't our focus now. 
Our focus now is the migration of Bitmask libraries latest version to Pixelated code.

I'll close this issue for now, it might be reopened in the future if it makes sense.
