### ISSUE TITLE
Pixelated-dispatcher: SSLError-- fingerprint mismatch!

### ISSUE THREAD

**Issue by bkate** [pixelated-project/pixelated-dispatcher#96]
After creating an user account and trying to log in to https://localhost:8080/ than I receive a fingerprint mismatch as illustrated bellow!

```
2015-04-14 12:18:53+0000 [-] Unhandled error in Deferred:
2015-04-14 12:18:53+0000 [-] Unhandled Error
        Traceback (most recent call last):
          File "/usr/lib/python2.7/threading.py", line 783, in __bootstrap
            self.__bootstrap_inner()
          File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
            self.run()
          File "/usr/lib/python2.7/threading.py", line 763, in run
            self.__target(*self.__args, **self.__kwargs)
        --- <exception caught here> ---
          File "/usr/lib/python2.7/dist-packages/twisted/python/threadpool.py", line 196, in _worker
            result = context.call(ctx, function, *args, **kwargs)
          File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
            return self.currentContext().callWithContext(ctx, func, *args, **kw)
          File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
            return func(*args,**kw)
          File "/usr/lib/python2.7/dist-packages/pixelated/config/__init__.py", line 66, in init_soledad
            return init_soledad_and_user_key(app, args.home)
          File "/usr/lib/python2.7/dist-packages/pixelated/config/soledad.py", line 24, in init_soledad_and_user_key
            leap_home)
          File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/session.py", line 41, in open
            provider = LeapProvider(server_name, config)
          File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 29, in __init__
            self.provider_json = self.fetch_provider_json()
          File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 109, in fetch_provider_json
            response = self._validated_get(url)
          File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 101, in _validated_get
            response = session.get(url, verify=which_bootstrap_CA_bundle(self), timeout=self.config.timeout_in_s)
          File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 469, in get
            return self.request('GET', url, **kwargs)
          File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
            resp = self.send(prep, **send_kwargs)
          File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
            r = adapter.send(request, **kwargs)
          File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 420, in send
            raise SSLError(e, request=request)
        requests.exceptions.SSLError: Fingerprints did not match. Expected "68f65834fa507f1b83c5d87f9a4994015ee5915f", got "ecad27f669aec4fa952f6e584a74d59c8d8a125f".
        
```

following steps were performed before: 
1. VB and Vagrant installation 
2. Vagrantfile configuration as in the documentation
3. Leap configuration
4. Add Pixelated to Leap Config

**Comment by cz8s** [comment]
The problem seems to stem from the fact that leap was installed multiple times on that machine.
But I found another problem: The user-agent running in the dispatcher has to connect to a provider
that is resolvable by dns. That does not work on test setup in vagrant.
I leave this ticket open until I have the chance to create a new one ...

**Comment by cz8s** [comment]
opend pixelated-user-agent/#380
Closing this as invalid
